INSERT INTO artefato 
	(	id,
		nome,
		quantidade,
		tipo,
		urlImagem
		,descricao) VALUES 
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),;