INSERT INTO artefato 
	(	id,
		nome,
		quantidade,
		tipo,
		urlImagem
		,descricao) VALUES 
	('Passaportes falsos',10, 'Droga', 'null','não usa sa pora não'),
	('Contas roubadas da Netflix',10, 'Documento', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),
	('Maconha',10, 'Droga', 'null','não usa sa pora não'),;